version: '3'

services:
  web:
    build: .
    command: web
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      BUNDLE_PATH: /bundle/vendor
      DB_USERNAME: db
      DB_PASSWORD: db
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql

volumes:
  app:
  bundle:
  db:
